dist: trusty
language: java
jdk:
  - openjdk8

env:
  - COVERAGE=0.057 BUILD_TARGET=./monolithic/ui

install:
  - ./gradlew clean jar

script:
  - ./gradlew -p $BUILD_TARGET check

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
