language: java
jdk:
  - openjdk8

services:
  - docker

env:
  - COVERAGE=0.057 BUILD_TARGET=./monolithic/ui

global:
  - DOCKER_LOGIN=justrules
  - secure: "l0azLzCyoGBasJXLtgGzyiw+I0t4pwgqqU7MBarVd+zBjF9urcSJJ67m71pOiQRTr9ScIpbbciytjimUaWNJ5GW+IC3+Bg2TcNqxJghY0qHjLKf1CTQIpk6CsI7xV+sD8+MiFokCPc7niaHvD0aFdMGpXUKQwpw01T9Q2Tfv+CjLFKGH/naYX1Xd5Njiz8TTuuRByYfF/DXsAgwdYIlhihecC8+wZxOqlvJuIE8+S6ZqQdRZv7ZfplPEp44xjMEHB/3PzmI404IkoXGLXKC6LGFQnk2H+9PNMY5D/L+JX5sjnoI4tRQOfqOVhPdAS3grObPvVpfOi3jcLfN+aHYRHnVVBQljViTfPgq0H3BLV8kMVJbS6/ksr3Am6zv3kvFZ3jcT3fQVa+gx5e3ID8gf9IQBpZUjGo+TXp7pOGU62Wldn0VyhQ+mzL/HnQlnJWyiLCfCUoOXFM/B8mgOi8QAuO6sW7WlgdAxZSnatrtsbR9j2kZXBzOp1pfHUTizX+Kit1+/o65HYYb0UMTQ/pe54NywbsD6zSDGrteIcBs+CTeUmojeaavcRSNRee9/SmOz4MJ2urffnXIKcHH6Pvc6BgL+YoyZWRfBkuDiKyqpmFzOVYOPZNn+aoj4aryzCzhPcTiTle6nvkelsOTCK37OkI5cavukAWk1l0WEgtwAfZg="

install:
  - ./gradlew clean jar

script:
  - ./gradlew -p $BUILD_TARGET check

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin ;"
#  script: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_LOGIN}" --password-stdin ;
  on:
    all_branches: true
