dist: trusty
language: java
jdk:
  - openjdk8

env:
  - COVERAGE=0.5

script:
  - ./gradlew clean jar
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

before_deploy:
  - ./gradlew jacocoTestCoverageVerification

deploy:
  - provider: script
    script: echo "WIP"
    on:
      all_branches: true