dist: trusty
language: java
jdk:
  - openjdk8

services:
  - docker

env:
  - COVERAGE=0.057 BUILD_TARGET=./monolithic/ui

global:
  - DOCKER_LOGIN=justrules
  - secure: "hXXrBD+Kz/iEGTcZXPpm2MBQOWAaxCMJSYef7nLSYtyaIwbyetRErJT5hsLKrEDwLiEHkDrmE3WERpBZ848m5DnI77G42rBjvBZ3REQFXdDJqfxwiELOXDYbdGC8h+ChDKZdNtm1Imstk24oar1Fno1/3ziAlyj8Xz49m5D6a2B1SbJHzdTe4L1Pc1lFZj9xiSm1hjauPz/dDKXU8E5EaHLOQ90iQJhqcWynGxZ/adsCJCnhN4fEAqwwXPR4HFxfTwJklrVlpFzyKNf9StbMRcZBsozMqBtaMacI8lBalyRG3tenw5ue7SDIY1fiRWs6BVqJ9xsI5dHOpre9vr/oiA6oiqcdbhji1AJX4bY0EnFlhs19NCWhPWnxJYq/X8S7kStbaGLOsJkoa01mGw2io7R5FWW8w0V3/Z4KG3lQto+sg2UCui3b3VIpPm68JJeDcuja2wfboFa3Hej8nbr/HeoIwwMw2XKQ2V1amFAzM0T4a/B5uxCAtsxfrQaDrNG3cZAo0WGhkiGblpsI62qX5pzzWhzCJfolBRGvXXwKhBmw91ClgfLr/XUtNMFFQ0xa72YChsg/h4o+h8GK9NuVEmAc81pSCvJRYrSfXxL+h0Ezy3m1h33ubkSNf/aMtJdMWsMv/TpCHhQvIIcm5sZSwkAocJnkQPoHGlusztIFk3g="

install:
  - ./gradlew clean jar

script:
  - ./gradlew -p $BUILD_TARGET check

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin ;"
  on:
    all_branches: true