language: java
jdk:
  - openjdk8

services:
  - docker

env:
  - COVERAGE=0.057 BUILD_TARGET=./monolithic/ui

global:
  - DOCKER_LOGIN=justrules
  - secure: "OjWHYgr2YmYq7s9IM0rAAgFZurhMKWZAuh7cJ/NMT0SxzpR4HtTz6bOyOx95LVIBYtLzsrBesBBn8HhBYTHD1aTyHCyKl3qbNkQBhHv0dptfRPjgLh80ix9321xeLSaNg1fdZ2I7rTKNEEtbn9jLQFm+z/9TmrrPqOBAAK3lqANVWNxvJEH3/2DKFvVPFVDDOoKxjThKo30WoXIOEFGzoLBvsyr/u9DfQZ+lWShwEpydvUR66WIPTpgQY6LXtcNbg4bsyaPIxMnzqivoXrMPYQV3u4NTQEa+W69iu0ta+wU/yRRR+NkbfltBM5qyOjrxmaO/2cjYE7QF/uvwVz5RK5yP4GZtuSMzY03Grxn+gGz177fMHXKQL45mIKGlH6IBrONeMVnQ49WeLBe0QDPqgrzViu4AG8lbkSmEwD/YfCIgkcnLTwYGegUlgA9o+G/m5iXAcoUUJcMFezkGommXMryd/bmOUbVWam0uEQMH2N/PQmbb4tFU+xjIsXpiqyxhQ8/mzG84JVHNbuQhnee/1NfedEANSEum0vZNrmdb4UNdh/Uid1g0T9jowzq7ICFo5QkHbvnVqhSRhkvuQ2268Emlle017pfF1zCfMEYV/YChlE89UK3sz7sn2Z0VD6H2HabcqJ5r8XqG/kLgxJSXB98T/i5iYYbqzQdlwrPEET4="

install:
  - ./gradlew clean jar

script:
  - ./gradlew -p $BUILD_TARGET check

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin ;"
  on:
    all_branches: true
