language: java
jdk:
  - openjdk8

services:
  - docker

env:
  - COVERAGE=0.057 BUILD_TARGET=./monolithic/ui

global:
#  - secure: "pYd2j1Cy3GxYM2wdGCS2w41RMkD9UFu7KwCvTqVDl/S31MGNqrlAIZbOsSP5h8YIO3A9k6SZt+Ncjg9RQ2xWFOHNTi+btIovpmTxR4lu3MfX6Fq0sTj0ygE6nQQWom1XkuNcxxuueYyqThD8NyxTUNelsSaJFKn4CJ8nBd9XBM7Y5AY6AjhIEiNdBdfE1S329rl4DOEhZSPlym6JzAL0niZ6OWzfYT6/PeZOM80mz/AbIe2+Hk6Knzo5Mn7xv0ZX+AbuikeyF4D9zkYV9k/d+Fbm+UT0k42kTnME5MM9rmnuS+6Aoa8uEv/n2jQpTrvHhDlDYZEpf6URT83oqv0hcVQuRoeigChYBjenEm2cqWXHkraFacXo9rlJZL4qGWashLPEVsVqHgKsNE+OwvXQaw+nz7YPkJdamnbGVXzYei2Cyai1KHZKoOAxdWGOstyhSawj37ZeZhNTQ/C8clF7TzZJy2M7fPM7zjD+e1CuoWC9S3hJrlqHWPgrwnblQ7nz0cCtaGfBOjETscf7n6wqJa+NpBf90NCCt4ipgQAXz7jZWzsv/MSsZr43vD+zlXZva7v/29RgmXUdaOT8BtlvVcCoxcJdarnGU+HIUpqWTzLdnkK0HsAbdx0VporUP+6rL1HrwwMhHtFwDQZdiOVvhI/lxBdNR79r8Es10f4hFrM="
#  - secure: "Dy8yW+LvgE/YwzMuxJlbCy0LFaRGs/fiQy+UwKVLVeYqtrxnZM/YV0Reh/+sWUf/0bgOjjNacUfH7a6EAH4IlFbilrb2FYWSaWxq4nYLV9Z6VteHObBR26C4D7Ak2BysLYw/GKalEOtT4KCa+mPZfIvnCNrqvbTIcWFkOkUCSntocRyIcF8hgOn9vSJA/njBNHl4m+lllmDFUlrMMJ2XDFPEsi6J0GsyGuDlqFTxJB7j45za9TWMWtm1YqfNYI/Ef7O9/ECEupKlVxnOWwLBC8wZ82WtaSFaIav4ga9xQygAtx+yvThNS/C9tFW9+gKIUb5nfGbrcdsJxbnJAHlMDnhnKdjw8E7B0doA8zOSO/h1gEu6hSU2VRUEXmcv+mtvqP53BukeuRrB6eN5DU02thNGmYu4aNCvVDH++XmNhpPRTZdF+nunY2aJ6o7pVFrmbWaFk8bFKuKDt3TUWHETyxfuE/D4tNcSPxhDcXMm6MI98FhE6DFteeTJWg8ZqMSgO/tjRm+9rAlWbv7hiY94ozWKyNZCNKtfJcJDWD+j+Ul+KawP4uh6a4sF3d0J/DxxGHicX0mTPSLY/XfoLWE8kyfeQK/JeNB8LBmokhYHz+S8YGWf3U3nXz2N0gHGH2wPjU8BzmvI/M/ZtKMOtqFBEKjTPOoRf4u8rWMixwSMUwA="
  - DOCKER_LOGIN="justrules"
  - DOCKER_PASSWORD="3cea24fc-542b-4aec-ae5b-bc839f185a59"

install:
  - ./gradlew clean jar

script:
  - ./gradlew -p $BUILD_TARGET check

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: 
    - bash -c "echo docker login -u="justrules" -p="3cea24fc-542b-4aec-ae5b-bc839f185a59";"
#    - bash -c "echo \justrules\ | docker login -u \3cea24fc-542b-4aec-ae5b-bc839f185a59\ --password-stdin ;"
#    - bash -c "echo \"${DOCKER_PASSWORD}\" | docker login -u \"${DOCKER_LOGIN}\" --password-stdin ;"
  on:
    all_branches: true
